
  var weekly_bet_club_list = [
      {
        "offer_description": "Bet £30, Get £5 Free Bet",
        "odds_details": "2.0",
        "bookmaker": "Skybet",
        "profit": "£1.50",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/skybet",
        "offer": "https://m.skybet.com/skybetclub",
        "logo": "https://static.wixstatic.com/media/7a0e3a_3b25d869c20042f38fc666d42118cedb~mv2.png",
      },
      {
        "offer_description": "Bet £10, Get £5 Free Bet",
        "odds_details": "2.0",
        "bookmaker": "BetUK",
        "profit": "£3",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/betuk",
        "offer": "https://www.betuk.com/promotions/football-always-on-bet-10-get-5-2",
        "logo": "https://static.wixstatic.com/media/7a0e3a_27a9ecf4eb2042bfb0ff1b09ecc0e202~mv2.png",
      },
      {
        "offer_description": "Bet £25, Get £5 Free Bet",
        "odds_details": "2.0",
        "bookmaker": "Midnite",
        "profit": "£2.75",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/midnite",
        "offer": "https://www.midnite.com/rewards",
        "logo": "https://static.wixstatic.com/media/7a0e3a_aef8f4249eb84014b9d101801ed16833~mv2.png",
      },
      {
        "offer_description": "Bet £50, Get £10 Free Bet",
        "odds_details": "2.0",
        "bookmaker": "BetVictor",
        "profit": "£3",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/betvictor",
        "offer": "https://www.betvictor.com/en-gb/offer/KY53",
        "logo": "https://static.wixstatic.com/media/7a0e3a_6bea71614dad44019eb7657e7fb97bb2~mv2.png",
      },
      {
        "offer_description": "Bet £50, Get £10 Free Bet",
        "odds_details": "2.0",
        "bookmaker": "TalkSPORT BET",
        "profit": "£5",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/talksport-bet",
        "offer": "https://www.talksportbet.com/en-gb/offer/XV35B",
        "logo": "https://static.wixstatic.com/media/7a0e3a_a5a4e2c5542e473682f225d0bff59052~mv2.png",
      },    
      {
        "offer_description": "Bet £50, Get £10 Free Bet",
        "odds_details": "3.0",
        "bookmaker": "StarSports",
        "profit": "£4",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/starsports",
        "offer": "https://starsports.bet/?account=static-resource-carousel-promo-terms&promoId=12010",
        "logo": "https://static.wixstatic.com/media/7a0e3a_59e5257dc642477abaa8702660ca3621~mv2.png",
      },
      {
        "offer_description": "Bet £100, Get £10 Free Bet",
        "odds_details": "2.0",
        "bookmaker": "Betway",
        "profit": "£2",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/betway",
        "offer": "https://betway.com/terms-and-conditions/en?promoid=1077056",
        "logo": "https://static.wixstatic.com/media/7a0e3a_2e3ef618674d4c94a2850b097873d5bb~mv2.png",
      },
      {
        "offer_description": "Bet £10, Get £5 Free Bet",
        "odds_details": "2.0",
        "bookmaker": "The Pools",
        "profit": "£1.50",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/the-pools",
        "offer": "https://www.thepools.com/promotions/weekly-bet-builder-offer",
        "logo": "https://static.wixstatic.com/media/7a0e3a_a90d9ef212ce4120bb4fb787efdc3376~mv2.png",
      },
      {
        "offer_description": "Bet £20, Get £5 Free Bet",
        "odds_details": "4.0",
        "bookmaker": "888Sport",
        "profit": "£2",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/888sport",
        "offer": "https://www.888sport.com/online-sports-betting-promotions/",
        "logo": "https://static.wixstatic.com/media/7a0e3a_39af396146c84a38a96e953f938290ef~mv2.png",
      },
      {
        "offer_description": "Bet £20, Get £5 Free Bet",
        "odds_details": "3.0",
        "bookmaker": "Virgin Bet",
        "profit": "£2",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/virgin-bet",
        "offer": "https://www.virginbet.com/promotions/65d5b6f2aef7e311c934a3be",
        "logo": "https://static.wixstatic.com/media/7a0e3a_d7313dc914d245acb174e5958627ce8e~mv2.png",
      },
      {
        "offer_description": "Bet £X, Get £X Free Bet",
        "odds_details": "2.0",
        "bookmaker": "Paddy Power",
        "profit": "£3",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/paddy-power",
        "offer": "https://promotions.paddypower.com/paddysrewardsclub",
        "logo": "https://static.wixstatic.com/media/7a0e3a_fcbb73ffbfa6454b8506f7a6e7e25c67~mv2.png",
      },
      {
        "offer_description": "Bet £25, Get £8 Free Bet",
        "odds_details": "4.0",
        "bookmaker": "Lottoland",
        "profit": "£4",
        "guide": "https://www.betterbetgroup.com/weekly-bet-club-offers/lottoland",
        "offer": "https://www.lottoland.co.uk/betclub",
        "logo": "https://static.wixstatic.com/media/7a0e3a_93219c714b554f309efa17e32bb84547~mv2.png",
      },

    ]

  
