(function () {

const weekly_bet_club_list = [
    {
      "offer_description": "Bet £30, Get £5 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "Sky Bet",
      "profit": "£1.50",
      "guide": "",
      "offer": "https://m.skybet.com/skybetclub",
      "logo": "https://static.wixstatic.com/media/7a0e3a_3b25d869c20042f38fc666d42118cedb~mv2.png",
    },
    {
      "offer_description": "Bet £10, Get £5 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "BetUK",
      "profit": "£3",
      "guide": "",
      "offer": "https://www.betuk.com/promotions/football-always-on-bet-10-get-5-2",
      "logo": "https://static.wixstatic.com/media/7a0e3a_27a9ecf4eb2042bfb0ff1b09ecc0e202~mv2.png",
    },
    {
      "offer_description": "Bet £25, Get £5 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "Midnite",
      "profit": "£2.75",
      "guide": "",
      "offer": "https://www.midnite.com/rewards",
      "logo": "https://static.wixstatic.com/media/7a0e3a_aef8f4249eb84014b9d101801ed16833~mv2.png",
    },
    {
      "offer_description": "Bet £50, Get £10 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "BetVictor",
      "profit": "£3",
      "guide": "",
      "offer": "https://www.betvictor.com/en-gb/offer/KY53",
      "logo": "https://static.wixstatic.com/media/7a0e3a_6bea71614dad44019eb7657e7fb97bb2~mv2.png",
    },
    {
      "offer_description": "Bet £30, Get £5 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "Vickers Bet",
      "profit": "£2.50",
      "guide": "",
      "offer": "https://www.vickers.bet/promotions/vickers-bet-club/",
      "logo": "https://static.wixstatic.com/media/7a0e3a_5e43d2ea7fb14e2f82be513b97aea470~mv2.png",
    },
    {
      "offer_description": "Bet £50, Get £10 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "TalkSPORT BET",
      "profit": "Varies",
      "guide": "",
      "offer": "https://www.talksportbet.com/en-gb/offer/XV35B",
      "logo": "https://static.wixstatic.com/media/7a0e3a_a5a4e2c5542e473682f225d0bff59052~mv2.png",
    },    
    {
      "offer_description": "Bet £50, Get £10 Free Bet",
      "odds_details": "3.0",
      "bookmaker": "StarSports",
      "profit": "£3",
      "guide": "",
      "offer": "https://starsports.bet/?account=static-resource-carousel-promo-terms&promoId=12010",
      "logo": "https://static.wixstatic.com/media/7a0e3a_59e5257dc642477abaa8702660ca3621~mv2.png",
    },
    {
      "offer_description": "Bet £100, Get £20 Free Bet",
      "odds_details": "1.5",
      "bookmaker": "Kwiff",
      "profit": "Varies",
      "guide": "",
      "offer": "https://promo.kwiff.com/sports-reward-club/",
      "logo": "https://static.wixstatic.com/media/7a0e3a_c2ecfb4964e3445a8989ac350cc547a6~mv2.png",
    },
    {
      "offer_description": "Bet £100, Get £10 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "BetWay",
      "profit": "£3",
      "guide": "",
      "offer": "https://betway.com/terms-and-conditions/en?promoid=1077056",
      "logo": "https://static.wixstatic.com/media/7a0e3a_2e3ef618674d4c94a2850b097873d5bb~mv2.png",
    },
    {
      "offer_description": "Bet £20, Get £10 Free Bet",
      "odds_details": "3.0",
      "bookmaker": "The Pools",
      "profit": "£6",
      "guide": "",
      "offer": "https://www.thepools.com/promotions/sports/weekly-acca-offer",
      "logo": "https://static.wixstatic.com/media/7a0e3a_a90d9ef212ce4120bb4fb787efdc3376~mv2.png",
    },
    {
      "offer_description": "Bet £20, Get £5 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "BetMGM",
      "profit": "£2",
      "guide": "",
      "offer": "https://www.betmgm.co.uk/",
      "logo": "https://static.wixstatic.com/media/7a0e3a_1be9e466f5754e22981886692d69deb8~mv2.png",
    },
    {
      "offer_description": "Bet £50, Get £5 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "CopyBet",
      "profit": "£1.50",
      "guide": "",
      "offer": "https://www.copybet.com/promo/weekly-challenge/",
      "logo": "https://static.wixstatic.com/media/7a0e3a_7639840a36854961bde4fda778d08807~mv2.png",
    },
    {
      "offer_description": "Bet £100, Get £10 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "BetZone",
      "profit": "£3",
      "guide": "",
      "offer": "https://betzone.co.uk/",
      "logo": "https://static.wixstatic.com/media/7a0e3a_d1e0766b549a409aa9fdcbfb03ebc900~mv2.png",
    },
    {
      "offer_description": "Bet £20, Get £5 Free Bet",
      "odds_details": "4.0",
      "bookmaker": "888Sport",
      "profit": "£2",
      "guide": "",
      "offer": "https://www.888sport.com/online-sports-betting-promotions/",
      "logo": "https://static.wixstatic.com/media/7a0e3a_39af396146c84a38a96e953f938290ef~mv2.png",
    },
    {
      "offer_description": "Bet £100, Get £10 Free Bet",
      "odds_details": "2.0",
      "bookmaker": "PlanetSportBet",
      "profit": "£3",
      "guide": "",
      "offer": "https://planetsportbet.com/",
      "logo": "https://static.wixstatic.com/media/7a0e3a_1ca0c9f5bb514a22ad2a42c2726bd1f1~mv2.png",
    },
    {
      "offer_description": "Bet £20, Get £5 Free Bet",
      "odds_details": "3.0",
      "bookmaker": "Virgin Bet",
      "profit": "£2",
      "guide": "",
      "offer": "https://www.virginbet.com/promotions/65d5b6f2aef7e311c934a3be",
      "logo": "https://static.wixstatic.com/media/7a0e3a_d7313dc914d245acb174e5958627ce8e~mv2.png",
    },
    {
      "offer_description": "Bet £X, Get £X Free Bet",
      "odds_details": "2.0",
      "bookmaker": "Paddy Power",
      "profit": "£3",
      "guide": "",
      "offer": "https://promotions.paddypower.com/paddysrewardsclub",
      "logo": "https://static.wixstatic.com/media/7a0e3a_fcbb73ffbfa6454b8506f7a6e7e25c67~mv2.png",
    },
  ]

})();
